# Generated by Django 4.2.4 on 2024-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Adminid', models.AutoField(primary_key=True, serialize=False)),
                ('Adminname', models.CharField(max_length=100)),
                ('Adminemail', models.EmailField(max_length=254, unique=True)),
                ('Adminpassword', models.CharField(max_length=20)),
                ('Adminphoneno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parentname', models.CharField(max_length=100)),
                ('Parentemail', models.EmailField(max_length=254, unique=True)),
                ('Parentpassword', models.CharField(max_length=20)),
                ('Parentphoneno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(max_length=100)),
                ('Teacheremail', models.EmailField(max_length=254, unique=True)),
                ('Teacherpassword', models.CharField(max_length=20)),
                ('Teacherphoneno', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
