# Generated by Django 4.2.4 on 2024-06-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0002_admin_parent_teacher_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
