# Generated by Django 4.2.4 on 2024-06-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kindergartenapp', '0003_delete_admin_delete_parent_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Admin_Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Parent_IC', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Parent_Password', models.CharField(max_length=100)),
                ('Parent_Name', models.CharField(max_length=100)),
                ('Parent_Email', models.EmailField(max_length=254)),
                ('Parent_Nophone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_IC', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Teacher_Password', models.CharField(max_length=100)),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Email', models.EmailField(max_length=254)),
                ('Teacher_Nophone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Registration_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Child_Name', models.CharField(max_length=100)),
                ('Child_Gender', models.CharField(max_length=10)),
                ('Child_BirthDate', models.DateField()),
                ('Child_ParentName', models.CharField(max_length=100)),
                ('Parent_contact', models.CharField(max_length=20)),
                ('Parent_email', models.EmailField(max_length=254)),
                ('Child_Address', models.TextField()),
                ('Parent_IC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Child_Name', models.CharField(max_length=100)),
                ('Payment_Details', models.TextField()),
                ('Payment_Date', models.DateField()),
                ('Parent_IC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Grade_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Child_Name', models.CharField(max_length=100)),
                ('Child_Subject', models.TextField()),
                ('Child_Grade', models.TextField()),
                ('Registration_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('Complain_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Complain_Date', models.DateField()),
                ('Complain_Description', models.TextField()),
                ('Parent_IC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
    ]
