# Generated by Django 4.2.4 on 2024-06-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
