# Generated by Django 4.2.4 on 2024-06-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0005_delete_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('Complain_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Parent_Name', models.CharField(max_length=100)),
                ('Complain_Date', models.DateField()),
                ('Complain_Description', models.TextField()),
                ('Parent_IC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
    ]
