# Generated by Django 4.2.4 on 2024-06-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0006_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
