# Generated by Django 4.2.4 on 2024-06-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0008_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
