# Generated by Django 4.2.4 on 2024-06-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0009_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Child_Name', models.CharField(max_length=100)),
                ('Payment_Details', models.FileField(blank=True, null=True, upload_to='payment_details/')),
                ('Payment_Date', models.DateField()),
                ('Parent_IC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
    ]
