# Generated by Django 4.2.4 on 2024-06-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
