# Generated by Django 4.2.4 on 2024-06-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kindergartenapp', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_Name', models.CharField(max_length=100)),
                ('Payment_Date', models.DateField()),
                ('Payment_Details', models.FileField(upload_to='receipts/')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kindergartenapp.parent')),
            ],
        ),
    ]
